# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ocr-scanner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read          # required for actions/checkout
      id-token: write         # required for azure/login OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'    # you can change to 24.x if you really need

      - name: Install dependencies
        run: npm install

      - name: Build (if present)
        run: npm run build --if-present

      - name: Test (if present)
        run: npm test --if-present

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_22D7A093175F447DA36418025973D028 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_345D7EC5F3C34FEB88F636872693ECB8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8A717B1B077B4C96A08AC96612ED447A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ocr-scanner'
          package: .
          clean: true           # cleans old files on the App Service before deploy
